#!/usr/bin/env python
# coding=utf-8


Script = [
    [
        # 文本格式设置
        "TextBGTestCase", "TextDefWordTestCase", "TextTypeWordTestCase",
        "TextNewTextXTestCase", "TextNewTextYTestCase", "TextTypeWord2TestCase",
        "TextCutTestCase", "TextChangeFontTestCase", "TextChangeSizeTestCase",
        "TextChangeSize2TestCase", "TextChangeBoldTestCase", "TextChangeItalicTestCase",
        "TextChangeShadowTestCase", "TextChangeUnderlineTestCase", "TextChangeStrikeTestCase",
        "TextChangeDropDownTestCase", "TextChangeWordColorTestCase", "TextChangeRowSpaceTestCase",
        "TextChangeSpaceTestCase", "TextParaNoSymTestCase", "TextParaSymSaveTestCase",
        "TextParaSymOpenTestCase", "TextParaSymPreviewTestCase", "TextParaIndentTestCase",
        "TextParaIncIndentTestCase", "TextParaIncIndentSaveTestCase", "TextParaIncIndentOpenTestCase",
        "TextParaIncIndentTimesTestCase", "TextParaIndentSym1TestCase", "TextParaIndentSym2TestCase",
        "TextParaDefSpaceTestCase", "TextParaChange2SpaceTestCase", "TextParaChange3SpaceTestCase",
        "TextParaChange3SpaceSaveTestCase", "TextParaChange3SpaceOpenTestCase",
        "TextParaChangeFontTestCase", "TextParaLineSpaceSettingTestCase", "TextParaSettingAlignTestCase",
        "TextParaSettingAlign2TestCase", "TextParaSettingIndentTestCase", "TextParaSettingIndentAddTestCase",
        "TextParaSettingIndentMaxTestCase", "TextParaSettingIndentSubTestCase",
        "TextParaSettingIndentMinTestCase",
        "TextParaSettingIndentSpeTestCase", "TextParaSettingIndentSpe2TestCase",
        "TextParaSettingIndentSpe3TestCase",
        "TextParaSettingIndentSpe4TestCase", "TextParaSettingIndentSpe5TestCase",
        "TextParaSettingIndentSpe6TestCase",
        "TextParaSettingIndentSpe7TestCase", "TextParaSettingIndentSpeSymTestCase",
        "TextParaSettingIndentSpeSym2TestCase",
        "TextParaSettingIndentSpeSym3TestCase", "TextParaSettingIndentSpaceQianTestCase",
        "TextParaSettingIndentSpaceQian2TestCase",
        "TextParaSettingIndentSpaceQian3TestCase", "TextParaSettingIndentSpaceQian4TestCase",
        "TextParaSettingIndentSpaceQian5TestCase",
        "TextParaSettingIndentSpaceQianTestCase", "TextParaSettingIndentSpaceQian2TestCase",
        "TextParaSettingIndentSpaceQian3TestCase",
        "TextParaSettingIndentSpaceQian4TestCase", "TextParaSettingIndentSpaceQian5TestCase",
        "TextParaSettingIndentSpaceRowTestCase",
        "TextParaSettingIndentSpaceRow1TestCase", "TextParaSettingIndentSpaceRow2TestCase",
        "TextParaSettingIndentSpaceRow3TestCase",
        "TextParaSettingIndentSpaceRow4TestCase", "TextParaSettingIndentSpaceRow5TestCase",
        "TextParaSettingIndentSpaceRow6TestCase",
        "TextParaSettingIndentSpaceRow7TestCase", "TextParaSettingIndentSpaceRow8TestCase",
        "TextParaSettingIndentSpaceRow9TestCase",
        "TextParaSettingIndentSpaceRow10TestCase", "TextParaSettingCloseTestCase",
        "TextParaSettingCancleTestCase",
        "TextParaSettingSaveTestCase", "TextParaSettingOpenTestCase",
    ],
    [
        "Start3DPPTTestCase", "OpenPPTTestCase",
        "Open3DPPTTestCase", "NewPageTestCase", "SavepptxAs3dpxTestCase",
        "ExitPlayingEscTestCase", "ExitPlayingRightTestCase",
        "NewFileEditNoSaveTestCase", "NewFileEditSaveTestCase", "NewFileNoEditTestCase",

        # 插入元素
        "InsertTextXTestCase", "InsertTextYTestCase",
        "InsertTextBGTestCase", "InsertWordArtTestCase",
        "InsertVideo3GPTestCase", "InsertVideoASFTestCase",
        "InsertVideoAVITestCase", "InsertVideoFLVTestCase",
        "InsertVideoMOVTestCase", "InsertVideoMP4TestCase",
        "InsertVideoMPEGTestCase", "InsertVideoRMTestCase",
        "InsertVideoRMVBTestCase", "InsertVideoWMVTestCase",
        "InsertAudioAPETestCase", "InsertAudioM4ATestCase",
        "InsertAudioM4RTestCase", "InsertAudioMP3TestCase",
        "InsertAudioWAVTestCase", "InsertAudioWMATestCase",
        "InsertChart3DHistogramTestCase", "InsertChart3DLineTestCase",
        "InsertChart3DPieTestCase", "InsertImageBMPTestCase",
        "InsertImageGIFTestCase", "InsertImageJPEGTestCase",
        "InsertImageJPGTestCase", "InsertImagePNGTestCase",
        "InsertImagePanoramaTestCase", "InsertImageWallTestCase",
        "InsertShapeAddTestCase", "InsertShapeArrowTestCase",
        "InsertShapeCircleTestCase", "InsertShapeLabelTestCase",
        "InsertShapeLineTestCase", "InsertShapeProcessTestCase",
        "InsertShapeRectangleTestCase", "InsertShapeStartTestCase",
        "Insert3DModelTestCase", "InsertTableQuickTestCase", "InsertTableCustomTestCase",
        # 选中元素
        "SelectOneTextTestCase", "SelectOneImageTestCase", "SelectOnePageTestCase",
        "SelectOneAudioTestCase", "SelectOneVideoTestCase", "SelectOne3DModelTestCase",
        "SelectOneChartTestCase", "SelectOneTableTestCase", "SelectOneShapeTestCase",
        # 复制粘贴元素
        "CopyPasteImageBMPTestCase", "CopyPasteImageGIFTestCase",
        "CopyPasteImageJPEGTestCase", "CopyPasteImageJPGTestCase",
        "CopyPasteImagePNGTestCase", "CopyPasteImageWallTestCase",
        "CopyPasteVideo3GPTestCase", "CopyPasteVideoASFTestCase",
        "CopyPasteVideoAVITestCase", "CopyPasteVideoFLVTestCase",
        "CopyPasteVideoMOVTestCase", "CopyPasteVideoMP4TestCase",
        "CopyPasteVideoMPEGTestCase", "CopyPasteVideoRMTestCase",
        "CopyPasteVideoRMVBTestCase", "CopyPasteVideoWMVTestCase",
        "CopyPasteAudioAPETestCase", "CopyPasteAudioM4ATestCase",
        "CopyPasteAudioM4RTestCase", "CopyPasteAudioMP3TestCase",
        "CopyPasteAudioWAVTestCase", "CopyPasteAudioWMATestCase",
        "CopyPasteChartHistogramTestCase", "CopyPasteChartLineTestCase",
        "CopyPasteChartPieTestCase", "CopyPasteShapeAddTestCase",
        "CopyPasteShapeArrowTestCase", "CopyPasteShapeCircleTestCase",
        "CopyPasteShapeLineTestCase", "CopyPasteShapeProcessTestCase",
        "CopyPasteShapeRectangleTestCase", "CopyPasteShapeStartTestCase",
        "CopyPastePageTestCase", "CopyPaste3DModelTestCase", "CopyPasteTableQuickTestCase",
        "CopyPasteTableCustomTestCase", "CopyPasteTextTestCase",
        # 超链接
        "HyperLinkTextBoxTestCase", "HyperLinkTextWordTestCase", "HyperLinkTextSpaceTestCase",
        "HyperLinkImageTestCase", "HyperLinkShapeTestCase", "HyperLinkShapeWebTestCase",
        # 图片设置边框
        "ImageBorderPanelTestCase", "ImageBorderEditTestCase", "ImageBorderClearTestCase",
        "ImageBorderTestCase",
        # 设置场景
        "ChangeThemesTestCase",
        # 剪切元素
        "CutTextTestCase", "CutImageTestCase", "CutAudioTestCase",
        "CutVideoTestCase", "CutShapeTestCase", "Cut3DModelTestCase",
        "CutChartTestCase", "CutTableTestCase", "CutPasteElementTestCase",
    ],
    [
        #
        # "ImageWallNumWarnTestCase", "ImageWallMaxNumTestCase",
        # "ImageWallAddTestCase", "ImageWallSubTestCase",
        # 旋转调整、远近调整
        # "ImageWallDistanceTestCase",

    ],
    [
        # 放映设置
        "PlayingFromCurrentTestCase", "PlayingFromFirstTestCase", "PlayingF5TestCase",
        # 上下页
        "PlayingSwitchPageArrowTestCase", "PlayingSwitchPagePgTestCase", "PlayingSwitchPageMouseWheelTestCase",
        # 拖动元素
        "SwipeTextTestCase", "SwipeImageTestCase", "SwipeAudioTestCase",
        "SwipeVideoTestCase", "Swipe3DModelTestCase",
        # 放映态菜单按钮功能
        "MenuFuncTextTestCase",
        "MenuFuncImageTestCase", "MenuFuncVideoTestCase", "MenuFuncAudioTestCase",
        "MenuFunc3DModelTestCase", "MenuFuncChartTestCase", "MenuFuncShapeTestCase",
        # 放映态复制粘贴
        "PlayingCopyPasteTextTestCase",
        "PlayingCopyPasteImageBMPTestCase", "PlayingCopyPasteImageGIFTestCase",
        "PlayingCopyPasteImageJPEGTestCase", "PlayingCopyPasteImageJPGTestCase",
        "PlayingCopyPasteImagePNGTestCase",
        "PlayingCopyPasteVideo3GPTestCase", "PlayingCopyPasteVideoASFTestCase",
        "PlayingCopyPasteVideoAVITestCase", "PlayingCopyPasteVideoFLVTestCase",
        "PlayingCopyPasteVideoMOVTestCase", "PlayingCopyPasteVideoMP4TestCase",
        "PlayingCopyPasteVideoMPEGTestCase", "PlayingCopyPasteVideoRMTestCase",
        "PlayingCopyPasteVideoRMVBTestCase", "PlayingCopyPasteVideoWMVTestCase",
        "PlayingCopyPasteAudioAPETestCase", "PlayingCopyPasteAudioM4ATestCase",
        "PlayingCopyPasteAudioM4RTestCase", "PlayingCopyPasteAudioMP3TestCase",
        "PlayingCopyPasteAudioWAVTestCase", "PlayingCopyPasteAudioWMATestCase",
        "PlayingCopyPasteChartHistogramTestCase", "PlayingCopyPasteChartLineTestCase",
        "PlayingCopyPasteChartPieTestCase", "PlayingCopyPasteShapeAddTestCase",
        "PlayingCopyPasteShapeArrowTestCase", "PlayingCopyPasteShapeCircleTestCase",
        "PlayingCopyPasteShapeLineTestCase", "PlayingCopyPasteShapeProcessTestCase",
        "PlayingCopyPasteShapeRectangleTestCase", "PlayingCopyPasteShapeStartTestCase",
        "PlayingCopyPaste3DModelTestCase",
    ],
    [],
    [
        # 视频播放设置
        "VideoPlayAutoTestCase", "VideoPlayClickTestCase",
        "VideoPlayCycleTestCase", "VideoPlayerHideTestCase",
        "VideoShowHidePageTestCase", "VideoShowPlayTestCase",
        "VideoShowStillPageTestCase", "VideoWindowNoTransTestCase",
        "Video3DBillBoardTestCase", "Video3DExBoardTestCase", "Video3DLDBillBoardTestCase",
        "Video3DMonitorTestCase", "Video3DOldTVTestCase",
        "Video3DPaintTestCase", "Video3DPhotoFrame1TestCase",
        "Video3DPhotoFrame2TestCase", "Video3DPhotoFrame3TestCase",
        "Video3DReelTestCase", "Video3DTVTestCase",
        # 音频播放设置
        "AudioBSSettingTestCase", "AudioPlayClickTestCase",
        "AudioPlayAutoTestCase", "AudioPlayCycleTestCase",
        "AudioPlayHideTestCase",
    ],
    [
        # 缩略图验证
        "ThumbnailMouseCoverTestCase", "ThumbnailMove2TestCase", "ThumbnailMove3TestCase",
        "ThumbnailMoveTestCase", "ThumbnailNewPageButtonTestCase", "ThumbnailNewPageEnterTestCase",
        "ThumbnailRightStageTestCase", "ThumbnailSelectMoreTestCase", "ThumbnailSelectMuchTestCase",
        "ThumbnailSelectRightTestCase"
    ],
    [
        # 形状属性设置
        "ShapeColorTestCase", "ShapeFormatTestCase", "ShapeLineTestCase",
        "ShapeLineTypeCircleTestCase", "ShapeLineTypeLongLineTestCase", "ShapeLineTypeLongSquareSquareTestCase",
        "ShapeLineTypeLongSquareTestCase", "ShapeLineTypeShortLineTestCase", "ShapeLineTypeShortSquareTestCase",
        "ShapeLineTypeSquareTestCase", "ShapeRectangleStyleTestCase", "ShapeRectangleTestCase",
        "ShapeTransparentTestCase",
    ],
    [
        "FarAndNearImageTestCase", "RotateXImageTestCase", "RotateYImageTestCase", "RotateZImageTestCase",
        "FarAndNearShapeTestCase", "RotateXShapeTestCase", "RotateYShapeTestCase", "RotateZShapeTestCase",
        "FarAndNearTextTestCase", "RotateXTextTestCase", "RotateYTextTestCase", "RotateZTextTestCase",
        "FarAndNearAudioTestCase", "RotateXAudioTestCase", "RotateYAudioTestCase", "RotateZAudioTestCase",
        "FarAndNearVideoTestCase", "RotateXVideoTestCase", "RotateYVideoTestCase", "RotateZVideoTestCase",
        "FarAndNear3DModelTestCase", "RotateX3DModelTestCase", "RotateY3DModelTestCase", "RotateZ3DModelTestCase",
        "Delete3DModelTestCase", "DeleteAudioTestCase", "DeleteChartTestCase",
        "DeleteImageTestCase", "DeleteShapeTestCase", "DeleteTableTestCase",
        "DeleteTextTestCase", "DeleteVideoTestCase",
        "ZoomOriginLeftImageTestCase", "ZoomOriginLeftTextTestCase", "ZoomOriginLeftAudioTestCase",
        "ZoomOriginLeftVideoTestCase", "ZoomOriginLeftShapeTestCase", "ZoomOriginLeft3DModelTestCase",
    ],
    [
        "SettingLogViewerTestCase",
        #保存提醒
        "CloseFileRemindTestCase", "NewFileRemindTestCase",
    ],

]

"""[
        "TextBGTestCase", "TextDefWordTestCase", "TextTypeWordTestCase",
        "TextNewTextXTestCase", "TextNewTextYTestCase", "TextTypeWord2TestCase",
        "TextCutTestCase", "TextChangeFontTestCase", "TextChangeSizeTestCase",
        "TextChangeSize2TestCase", "TextChangeBoldTestCase", "TextChangeItalicTestCase",
        "TextChangeShadowTestCase", "TextChangeUnderlineTestCase", "TextChangeStrikeTestCase",
        "TextChangeDropDownTestCase", "TextChangeWordColorTestCase", "TextChangeRowSpaceTestCase",
        "TextChangeSpaceTestCase", "TextParaNoSymTestCase", "TextParaSymSaveTestCase",
        "TextParaSymOpenTestCase", "TextParaSymPreviewTestCase", "TextParaIndentTestCase",
        "TextParaIncIndentTestCase", "TextParaIncIndentSaveTestCase", "TextParaIncIndentOpenTestCase",
        "TextParaIncIndentTimesTestCase", "TextParaIndentSym1TestCase", "TextParaIndentSym2TestCase",
        "TextParaDefSpaceTestCase", "TextParaChange2SpaceTestCase", "TextParaChange3SpaceTestCase",
        "TextParaChange3SpaceSaveTestCase", "TextParaChange3SpaceOpenTestCase",
        "TextParaChangeFontTestCase", "TextParaLineSpaceSettingTestCase", "TextParaSettingAlignTestCase",
        "TextParaSettingAlign2TestCase", "TextParaSettingIndentTestCase", "TextParaSettingIndentAddTestCase",
        "TextParaSettingIndentMaxTestCase", "TextParaSettingIndentSubTestCase", "TextParaSettingIndentMinTestCase",
        "TextParaSettingIndentSpeTestCase", "TextParaSettingIndentSpe2TestCase", "TextParaSettingIndentSpe3TestCase",
        "TextParaSettingIndentSpe4TestCase", "TextParaSettingIndentSpe5TestCase", "TextParaSettingIndentSpe6TestCase",
        "TextParaSettingIndentSpe7TestCase", "TextParaSettingIndentSpeSymTestCase", "TextParaSettingIndentSpeSym2TestCase",
        "TextParaSettingIndentSpeSym3TestCase", "TextParaSettingIndentSpaceQianTestCase", "TextParaSettingIndentSpaceQian2TestCase",
        "TextParaSettingIndentSpaceQian3TestCase", "TextParaSettingIndentSpaceQian4TestCase", "TextParaSettingIndentSpaceQian5TestCase",
        "TextParaSettingIndentSpaceQianTestCase", "TextParaSettingIndentSpaceQian2TestCase", "TextParaSettingIndentSpaceQian3TestCase",
        "TextParaSettingIndentSpaceQian4TestCase", "TextParaSettingIndentSpaceQian5TestCase", "TextParaSettingIndentSpaceRowTestCase",
        "TextParaSettingIndentSpaceRow1TestCase", "TextParaSettingIndentSpaceRow2TestCase", "TextParaSettingIndentSpaceRow3TestCase",
        "TextParaSettingIndentSpaceRow4TestCase", "TextParaSettingIndentSpaceRow5TestCase", "TextParaSettingIndentSpaceRow6TestCase",
        "TextParaSettingIndentSpaceRow7TestCase", "TextParaSettingIndentSpaceRow8TestCase", "TextParaSettingIndentSpaceRow9TestCase",
        "TextParaSettingIndentSpaceRow10TestCase", "TextParaSettingCloseTestCase", "TextParaSettingCancleTestCase",
        "TextParaSettingSaveTestCase", "TextParaSettingOpenTestCase", 
    ],[
        "Start3DPPTTestCase2","Start3DPPTTestCase", "OpenPPTTestCase",
        "Open3DPPTTestCase", "NewPageTestCase",
        "SavepptxAs3dpxTestCase", "NewFileNoEditTestCase",
        "NewFileEditNoSaveTestCase", "NewFileEditSaveTestCase",
        "InsertTextXTestCase", "InsertTextYTestCase",
        "InsertTextBGTestCase", "InsertWordArtTestCase",
        "InsertVideo3GPTestCase", "InsertVideoASFTestCase",
        "InsertVideoAVITestCase", "InsertVideoFLVTestCase", 
        "InsertVideoMOVTestCase", "InsertVideoMP4TestCase",
        "InsertVideoMPEGTestCase", "InsertVideoRMTestCase", 
        "InsertVideoRMVBTestCase", "InsertVideoWMVTestCase",
        "InsertAudioAPETestCase", "InsertAudioM4ATestCase",
        "InsertAudioM4RTestCase", "InsertAudioMP3TestCase", 
        "InsertAudioWAVTestCase", "InsertAudioWMATestCase",
        "InsertChart3DHistogramTestCase", "InsertChart3DLineTestCase",
        "InsertChart3DPieTestCase", "InsertImageBMPTestCase",
        "InsertImageGIFTestCase", "InsertImageJPEGTestCase",
        "InsertImageJPGTestCase", "InsertImagePNGTestCase",
        "InsertImagePanoramaTestCase", "InsertImageWallTestCase", 
        "InsertShapeAddTestCase", "InsertShapeArrowTestCase", 
        "InsertShapeCircleTestCase", "InsertShapeLabelTestCase", 
        "InsertShapeLineTestCase", "InsertShapeProcessTestCase", 
        "InsertShapeRectangleTestCase", "InsertShapeStartTestCase", 

        "InsertCoursewareWholeTestCase", "InsertCoursewareOneTestCase", "Insert3DResourceTestCase"
        "InsertCefWordCardTestCase", "InsertMediaResourceTestCase", "InsertExerciseTestCase",
        "InsertInteractExerciseTestCase"

        "Insert3DModelTestCase", "CopyPasteTextTestCase", 
        "CopyPasteImageBMPTestCase", "CopyPasteImageGIFTestCase",
        "CopyPasteImageJPEGTestCase", "CopyPasteImageJPGTestCase",
        "CopyPasteImagePNGTestCase", "CopyPasteImageWallTestCase", 
        "CopyPasteVideo3GPTestCase", "CopyPasteVideoASFTestCase", 
        "CopyPasteVideoAVITestCase", "CopyPasteVideoFLVTestCase", 
        "CopyPasteVideoMOVTestCase", "CopyPasteVideoMP4TestCase", 
        "CopyPasteVideoMPEGTestCase", "CopyPasteVideoRMTestCase", 
        "CopyPasteVideoRMVBTestCase", "CopyPasteVideoWMVTestCase", 
        "CopyPasteAudioAPETestCase", "CopyPasteAudioM4ATestCase",
        "CopyPasteAudioM4RTestCase", "CopyPasteAudioMP3TestCase",
        "CopyPasteAudioWAVTestCase", "CopyPasteAudioWMATestCase",
        "CopyPasteChartHistogramTestCase", "CopyPasteChartLineTestCase",
        "CopyPasteChartPieTestCase", "CopyPasteShapeAddTestCase",
        "CopyPasteShapeArrowTestCase", "CopyPasteShapeCircleTestCase",
        "CopyPasteShapeLineTestCase", "CopyPasteShapeProcessTestCase",
        "CopyPasteShapeRectangleTestCase", "CopyPasteShapeStartTestCase",
        "CopyPastePageTestCase", "CopyPaste3DModelTestCase", "CopyPasteTableQuickTestCase",
        "CutPasteElementTestCase", "RestoreWindowTestCase",
        "MaxWindowedTestCase", "HyperLinkTextBoxTestCase",
        "HyperLinkTextWordTestCase", "HyperLinkTextSpaceTestCase",
        "HyperLinkImageTestCase", "HyperLinkShapeTestCase",
        "HyperLinkShapeWebTestCase", "ExitPlayingRightTestCase",
        "ExitPlayingEscTestCase", "SettingFloatTestCase",
        "SettingLanguageTestCase", "SettingCheckUpdateTestCase",
        "SettingAboutUsTestCase", "InsertTableQuickTestCase",
        "ImageBorderPanelTestCase", "ImageBorderEditTestCase", "ImageBorderClearTestCase",
        "ImageBorderTestCase", "ChangeThemesTestCase",
    ],[
        "ImageWallNumWarnTestCase", "ImageWallMaxNumTestCase",
        "ImageWallAddTestCase", "ImageWallSubTestCase", "ImageWallDistanceTestCase",
        "ImageWallSizeTestCase", "ImageWallShowEditTestCase",
        "ImageWallImageNumTestCase", "ImageWallsEditTestCase",
        "ImageWallPlayModeTestCase", "ImageWallPlayingTestCase",
        "ImageWallRightFormatTestCase", "ImageWallShowTypeTestCase",
        "ImageWallBtnAddTestCase", "ImageWallDlgTestCase",
        "ImageWallDlgShowTypeTestCase", "ImageWallShowTypeListTestCase", 
        "ImageWallImageListTestCase",

    ],[
        "PlayingFromCurrentTestCase", "PlayingFromFirstTestCase", "PlayingF5TestCase",
        "PlayingSwitchPageArrowTestCase", "PlayingSwitchPagePgTestCase", 
        "PlayingSwitchPageMouseWheelTestCase", "PlayingCopyPasteTextTestCase", 
        "PlayingCopyPasteImageBMPTestCase", "PlayingCopyPasteImageGIFTestCase", 
        "PlayingCopyPasteImageJPEGTestCase", "PlayingCopyPasteImageJPGTestCase",
        "PlayingCopyPasteImagePNGTestCase", "PlayingCopyPasteImageWallTestCase", 
        "PlayingCopyPasteVideo3GPTestCase", "PlayingCopyPasteVideoASFTestCase", 
        "PlayingCopyPasteVideoAVITestCase", "PlayingCopyPasteVideoFLVTestCase",
        "PlayingCopyPasteVideoMOVTestCase", "PlayingCopyPasteVideoMP4TestCase", 
        "PlayingCopyPasteVideoMPEGTestCase", "PlayingCopyPasteVideoRMTestCase",
        "PlayingCopyPasteVideoRMVBTestCase", "PlayingCopyPasteVideoWMVTestCase",
        "PlayingCopyPasteAudioAPETestCase", "PlayingCopyPasteAudioM4ATestCase",
        "PlayingCopyPasteAudioM4RTestCase", "PlayingCopyPasteAudioMP3TestCase",
        "PlayingCopyPasteAudioWAVTestCase", "PlayingCopyPasteAudioWMATestCase",
        "PlayingCopyPasteChartHistogramTestCase", "PlayingCopyPasteChartLineTestCase",
        "PlayingCopyPasteChartPieTestCase", "PlayingCopyPasteShapeAddTestCase",
        "PlayingCopyPasteShapeArrowTestCase", "PlayingCopyPasteShapeCircleTestCase",
        "PlayingCopyPasteShapeLineTestCase", "PlayingCopyPasteShapeProcessTestCase",
        "PlayingCopyPasteShapeRectangleTestCase", "PlayingCopyPasteShapeStartTestCase",
        "PlayingCopyPaste3DModelTestCase","MenuFuncImageTestCase",
        "MenuFuncVideoTestCase", "MenuFuncAudioTestCase", "MenuFunc3DModelTestCase",
        "MenuFuncChartTestCase", "MenuFuncShapeTestCase", "MenuFuncTextTestCase",
    ], [
        "CloseDlgTransitionsTestCase", "OpenDlgTransitionsTestCase",
    ], [
        "AudioPanelShowTestCase", "AudioPlayDisplayTestCase", "AudioPlayHideTestCase",
    ]
"""